FROM node:20-slim AS env

WORKDIR /srv/app

RUN apt-get update && \
    npm install -g http-server @vue/cli @vue/cli-service-global


FROM env AS build

COPY /app .
RUN npm -y install

RUN npm run build


FROM nginx AS publish

EXPOSE 80

COPY --from=build /srv/app/dist /usr/share/nginx/html